version: 2
jobs:
  build:
    working_directory: ~/projet-groupe-18
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: activity_main.xml
      - run: User.java
  test:
    working_directory: ~/projet-groupe-18
      docker:
        - image: circleci/android:api-28-alpha
      steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: Testcase101.java
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
  build:
    working_directory: ~/projet-groupe-18
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: activity_client_login.xml
      - run: activity_client_sign_up.xml
      - run: activity_client_welcome.xml
      - run: Client.java
  test:
    working_directory: ~/projet-groupe-18
      docker:
        - image: circleci/android:api-28-alpha
      steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: Testcase102.java
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
  build:
    working_directory: ~/projet-groupe-18
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: activity_cook_login.xml
      - run: activity_cook_sign_up.xml
      - run: activity_cook_welcome.xml
      - run: Cook.java
  test:
    working_directory: ~/projet-groupe-18
      docker:
        - image: circleci/android:api-28-alpha
      steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: Testcase103.java
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
  build:
    working_directory: ~/projet-groupe-18
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: activity_admin_login.xml
      - run: activity_admin_welcome.xml
      - run: activity_cook_login.xml
      - run: activity_cook_welcome.xml
      - run: Admin.java
      -run: Cook.java
  test:
    working_directory: ~/projet-groupe-18
      docker:
        - image: circleci/android:api-28-alpha
      steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: Testcase104.java
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
